### PR TITLE
Fix non-English locale issue

### LINKED ISSUE #3: /wymeditor/lang/zh-TW.js not found
When I update the latest version, my refinerycms editor return

/wymeditor/lang/zh-TW.js not found error.

I check out the console, zh-TW.js was stored as "zh_tw.js":
~/.rvm/gems/ruby-2.0.0-p353@rails4/bundler/gems/refinerycms-wymeditor-4aa3df90cc37/app/assets/javascripts/wymeditor/lang
bg.js  da.js  es.js  fr.js  it.js  nb.js  pl.js     rs.js  sl.js  vi.js
ca.js  de.js  fa.js  he.js  ja.js  nl.js  pt-BR.js  ru.js  sv.js  zh_cn.js
cs.js  en.js  fi.js  hu.js  lv.js  nn.js  pt.js     sk.js  tr.js  zh_tw.js

Can the zh_tw.js rename to zh-TW , like 'pt-BR.js' (so as zh_cn.js) ?

### PR DESCRIPTION
**Pull request by evenreven**
Attempt to fix #3

May be a bad idea for reasons unknown to me (the `i18n.locale` might be unsafe to use in this context, for instance), and the hardcoding of the base path `wymeditor/lang/` might be bad, but at least this fix works in my application without needing to hardcode the locale or disabling asset digest URLs.

The way this is done can probably be improved. But since asset_path is basically the only way to get this URL, I think it's an improvement this way.

EDIT: Cleaned up commit history.

### CODE REVIEW

**Comment by evenreven** [comment]
The travis check fails because of an old Ruby version, it seems. :)

**Comment by parndt** [comment]
@evenreven pull the latest master into your branch 😄

File: app/assets/javascripts/wymeditor/prototypes.js.erb [hunk 1]
```diff
@@ -556,7 +556,7 @@ WYMeditor.editor.prototype.replaceStrings = function(sVal) {
   var wym = this;
   if(!WYMeditor.STRINGS[wym._options.lang]) {
     try {
-      eval($.ajax({url:wym._options.langPath + wym._options.lang + '.js', async:false}).responseText);
+      eval($.ajax({url:"<%= asset_path("wymeditor/lang/#{I18n.locale}") %>", async:false}).responseText);
```
Comment (parndt) [inline app/assets/javascripts/wymeditor/prototypes.js.erb]: Does this value change in production when the language is changed, without recompiling assets?

Comment (evenreven) [reply app/assets/javascripts/wymeditor/prototypes.js.erb]: Good question, I was worried there for a second, but I tried it now, and it seems to work. I guess it's because all the languages available are in the assets directory anyway (I have plenty I don't need, which is fine) and this line is just about picking up the right one for display. 

Granted, I only have two locales (`nb` and `en`), and English is the fallback, so I have no idea whether or not it would with three backend locales running. (But that's probably kind of an edge case anyway, isn't it?)

**Comment by evenreven** [comment]
> @evenreven pull the latest master into your branch smile

Done! Checks passed now.

**Comment by evenreven** [comment]
:+1: 

Will you release a new version to rubygems or should I just put the master branch in my Gemfile from now on? 

Also, dumb question: I will stay on the 4.0-stable branch of Refinery CMS for the foreseeable future since we have a lot of Globalize-specific code in our templates and helpers. The Mobility-related code you added to master is just tests, right? They won't be a problem?

**Comment by parndt** [comment]
Yeah, just tests. The library was hooking into Globalize, but Globalize disappeared from the dependencies.

All of your Globalize code should be able to be switched out for Mobility code, they have very similar APIs...

I've just pushed version 2.1.0 to rubygems.org
