### PR TITLE
Use a request to load /wymiframe, which fixes #15

### LINKED ISSUE #15: wymeditor could not find all assets
I have to include following assets directly into my public folder:

    public/assets/refinery/formatting.css
    public/assets/refinery/theme.css
    public/assets/wymeditor/lang/de.js
    public/assets/skins/refinery/wymiframe.css

to remove a few 404 errors.. why are these files not loaded correctly through the rails asset pipeline?

Further I have a problem with precompiled assets:

    "NetworkError: 404 Not Found - http://my-domain.com/assets/wymeditor/skins/refinery/html5/h1-34fd10a7c7f09d1652329c96543a039e.png"
    "NetworkError: 404 Not Found - http://my-domain.com/assets/wymeditor/skins/refinery/html5/p-e482be71ffd131e6c25340378e37ae98.png

And if I take a look into my public assets folder on production I can see following files in the public/assets/wymeditor/skins/refinery/html5 directory:

    h1-8822cc5e930e7e2fe2d754b4ea64780c.png
    h1.png
    p-8d766d51f785ed9f10b2d934e29b79ef.png
    p.png

So is there something cached for the wymeditor? Or why does the editor requests "old" precompiled assets? If I use the h2-tag odr h3-tag I also get the same 404 not found error.
Any ideas what I am doing wrong or what could solve my problem?

I only have these problems on production btw.

### PR DESCRIPTION
**Pull request by parndt**
Previously we had a situation where we didn't need to call /wymiframe per iframe but that was doing weird things with assets so this puts that back in place, which fixes issue #15

### CODE REVIEW

**Comment by riceboy6888** [comment]
Thanks @parndt. It's working !

File: app/assets/javascripts/refinery/boot_wym.js.erb [hunk 1]
```diff
@@ -213,12 +213,6 @@ WYMeditor.editor.prototype.loadIframe = function(iframe) {
   if(doc.document) {
     doc = doc.document;
   }
-  if (!$.browser.msie) {
```
Comment (simi) [inline app/assets/javascripts/refinery/boot_wym.js.erb]: Do you remember why this was added? I can remember some IE crashes.

**Comment by simi** [comment]
Great @parndt.

File: app/assets/javascripts/refinery/boot_wym.js.erb (hunk 1 above)
Comment (parndt) [inline app/assets/javascripts/refinery/boot_wym.js.erb]: Because IE couldn't handle the dynamic loading code, but the others could. Now that it is removed it is unnecessary.

Comment (simi) [inline app/assets/javascripts/refinery/boot_wym.js.erb]: thanks @parndt
